# Project-wide Gradle settings.
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Estilo de código do Kotlin
kotlin.code.style=official

# Ativa o suporte nativo ao AndroidX
android.useAndroidX=true

# Desativa o Jetifier para evitar a mutação do classpath durante o build
android.enableJetifier=false

# Desativa o Configuration Cache incompatível
org.gradle.configuration-cache=false
ksp.incremental=false